language: c

os:
  - osx

before_install:
  - brew update
  - brew unlink python@2

script:
  # test regular build
  - travis_wait 30 brew install ./tiledb.rb
  - travis_wait 30 brew test ./tiledb.rb
  - travis_wait 30 brew uninstall tiledb
