language: c

os:
  - osx

osx_image: xcode12.5

before_install:
  - brew update

script:
  # test regular build
  - travis_wait 30 brew install ./tiledb.rb
  - travis_wait 30 brew test ./tiledb.rb
  - travis_wait 30 brew uninstall tiledb
