language: c

os:
  - osx

before_install:
  - brew update
  # required for tbb dependency
  - brew unlink python && brew install python2 || true
  - brew link --overwrite python@2

script:
  # test regular build
  - brew install ./tiledb.rb
  - brew test ./tiledb.rb
  - brew uninstall tiledb

  # test head build
  - brew install ./tiledb.rb --HEAD
  - brew test tiledb
  - brew uninstall tiledb

